### ISSUE TITLE
Readium WebPub manifest instance links to JSON-LD context, what about JSON-Schema?

### ISSUE THREAD

**Issue by danielweck** [readium/webpub-manifest#10]
Should the Readium2 streamer implementations produce an additional link to reference the JSON-Schema?
For example:
https://github.com/readium/webpub-manifest/blob/master/README.md#example
...links via `@context` to the JSON-LD URI:
https://readium.org/webpub-manifest/context.jsonld
...but we could also use the recommended type and rel for JSON-Schema draft-v7:
https://json-schema.org/draft-07/json-schema-release-notes.html#linking-instances-and-schemas

**Comment by HadrienGardeur** [comment]
It's really up to you. 

I'm not sure if this will really bring a lot of value, except for the rare case where someone would discover this JSON document in the wild, without any prior knowledge about RWPM.

It's also worth pointing out that JSON Schema itself is not completely stable, as illustrated by https://json-schema.org/draft-07/json-schema-release-notes.html#linking-instances-and-schemas
