### ISSUE TITLE
OPDS: How to link to a publication without an official media type (e.g. ZAB)?

### ISSUE THREAD

**Issue by mickael-menu** [readium/webpub-manifest#100]
We have an OPDS catalog that needs to serve Zipped Audio Books (a ZIP with audio files, without any manifest). This type of audiobook is very common in the wild.

Unfortunately, there's no official media type to identify a ZAB, except for `application/zip`. How can an OPDS client determine if an acquisition link without a media type is supported by the app?

For technical reasons, we added in the Readium toolkits [a custom internal media type for ZABs](https://readium.org/architecture/proposals/001-media-type.html#constants): `application/x.readium.zab+zip`. This could be used but might not be very interoperable. Note that W3C WebPub Manifests don't have any media type either.

Do we need an additional `conformsTo` property for an acquisition link, for these cases?

**Comment by HadrienGardeur** [comment]
> Unfortunately, there's no official media type to identify a ZAB, except for `application/zip`. How can an OPDS client determine if an acquisition link without a media type is supported by the app?

I wouldn't mint a new media type in this case, but probably use another hint that this is an audiobook.

Two things comes to mind:

- `@type` can be used to indicate that the publication is actually an audiobook (https://schema.org/Audiobook)
- through `indirectAcquisition` you could indicate that the ZIP is actually a mean of getting a bunch of audio files

Taken together, this would look something like that:

```json
"metadata": {
  "@type": "https://schema.org/Audiobook"
},
"links": [
  {
    "href": "https://example.com/audiobook.zip",
    "rel": "http://opds-spec.org/acquisition",
    "type": "application/zip",
    "properties": {
      "indirectAcquisition": [{"type": "audio/mpeg"}]
    }
  }
]
```

**Comment by HadrienGardeur** [comment]
Also, this might be a better fit for a discussion on https://github.com/opds-community/drafts or on the OPDS channel in Readium/EDRlab Slack.

**Comment by mickael-menu** [comment]
I like the solution with `indirectAcquisition`, because it also allows to say up front if the content of the ZAB is readable on the device (e.g. not ogg on iOS).
However it also puts more burden on the catalog/backend.

@sgarciac Do you think that's feasible?

**Comment by mickael-menu** [comment]
I have one doubt: so far we used `indirectAcquisition` for a LCPL file which contains itself a link to another file. Here's it's a bit different, we have one container which may contain several resources with different media types.

**Comment by HadrienGardeur** [comment]
In early examples and discussions about `indirectAcquisition` we also had that as an example.

**Comment by sgarciac** [comment]
> I like the solution with `indirectAcquisition`, because it also allows to tell up front if the content of the ZAB is readable on the device (e.g. not ogg on iOS). However it also puts more burden on the catalog/backend.
> 
> @sgarciac Do you think that's feasible?

ça devrait être possible, oui
