### ISSUE TITLE
JSON Schema - metadata.rendition?

### ISSUE THREAD

**Issue by danielweck** [readium/webpub-manifest#15]
`metadata.rendition.(layout|orientation|overflow)`

Currently parsed from EPUB (OPF XML):

`metadata.rendition.layout` = OPF `/package/metadata/meta/` `@property` ("rendition:layout") + `text()` ("pre-paginated" becomes "fixed", but otherwise "reflowable" remains)

`metadata.rendition.orientation` = OPF `/package/metadata/meta/` `@property` ("rendition:orientation") + `text()`

`metadata.rendition.overflow` = OPF `/package/metadata/meta/` `@property` ("rendition:flow") + `text()`

**Comment by danielweck** [comment]
Seems to be missing from https://github.com/readium/webpub-manifest/blob/master/schema/metadata.schema.json

**Comment by danielweck** [comment]
Implementation detail: note that `metadata.rendition.(layout|orientation|overflow)` is actually a 'properties' object structure which also includes `page|spread|encrypted|contains|media-overlay` because it is currently used for `link` properties.
Related issue: https://github.com/readium/webpub-manifest/issues/16

**Comment by danielweck** [comment]
Related issue: https://github.com/readium/webpub-manifest/issues/8

**Comment by HadrienGardeur** [comment]
Extensions are not covered as part of the JSON Schema for now, I'd like to keep it as-is for some time and figure this out later.
