### ISSUE TITLE
JSON Schema - link.properties?

### ISSUE THREAD

**Issue by danielweck** [readium/webpub-manifest#16]
Currently as unspecified `object`:
https://github.com/readium/webpub-manifest/blob/ca6d887caa2d0495200fef4695f41aacb5fed2e9/schema/link.schema.json#L29-L32

...but should be:
`layout|orientation|overflow|page|spread|encrypted|contains|media-overlay`

Related issue: https://github.com/readium/webpub-manifest/issues/15

**Comment by danielweck** [comment]
Related issue: https://github.com/readium/webpub-manifest/issues/8

**Comment by HadrienGardeur** [comment]
Same comment as #15, a good portion of these are in the EPUB extension which is not covered by the JSON Schema for now.

**Comment by danielweck** [comment]
Related OPDS issue: https://github.com/opds-community/drafts/issues/20
