### ISSUE TITLE
JSON Schema - publication.toc|page-list|landmarks|loi|loa|lov|lot

### ISSUE THREAD

**Issue by danielweck** [readium/webpub-manifest#17]
Seem to be missing from https://github.com/readium/webpub-manifest/blob/0ac78ab5c270a608c39b4b04fc90bd9b1d281896/schema/publication.schema.json

**Comment by danielweck** [comment]
Related issue: https://github.com/readium/webpub-manifest/issues/8

**Comment by HadrienGardeur** [comment]
I'll add `toc` since it got moved to the main spec but otherwise, same comment as #15.
