### ISSUE TITLE
JSON Schema - link.children? (TOC)

### ISSUE THREAD

**Issue by danielweck** [readium/webpub-manifest#19]
Currently unspecified (EPUB extension):
https://github.com/readium/webpub-manifest/blob/ca6d887caa2d0495200fef4695f41aacb5fed2e9/schema/link.schema.json

Regarding TOC, also see comment:
https://github.com/readium/webpub-manifest/issues/17#issuecomment-450135277

Related issues:
https://github.com/readium/webpub-manifest/issues/16
https://github.com/readium/webpub-manifest/issues/8

**Comment by HadrienGardeur** [comment]
This has been added to the schema at https://github.com/readium/webpub-manifest/blob/master/schema/link.schema.json#L57
