### ISSUE TITLE
archive.org audio-book webpub manifest, incorrect bitrate JSON type

### ISSUE THREAD

**Issue by danielweck** [readium/webpub-manifest#20]
I'm not sure where to file this issue, @HadrienGardeur could you please advise? The reason I am filing this here is because I am in the process of extending the `r2-xxx-js` unit tests to include the `archive.org` OPDS1 feed + (audio) webpubs (in addition to the OPDS2 Feedbooks feed), and this is how I discovered the `bitrate` JSON error (I am currently using a workaround to eliminate false negatives).

`bitrate` is a number, not a string:

https://github.com/readium/webpub-manifest/blob/20c426d87d9d75f02bec0dde2bfac3010fbbfa43/schema/link.schema.json#L47-L51

Incorrect:

https://api.archivelab.org/books/4thyearanticipations_1812_librivox/opds_audio_manifest

```json
"readingOrder": [
{
"bitrate": "113",
"href": "http://archive.org/download/4thyearanticipations_1812_librivox/4thyearanticipations_00_wells.mp3",
"title": "00 - Preface",
"duration": 678,
"type": "audio/mpeg"
}
]
```

**Comment by HadrienGardeur** [comment]
I've sent them the link to this issue on Slack.

**Comment by HadrienGardeur** [comment]
I'm closing this issue and suggest opening a separate one at https://github.com/internetarchive/openlibrary
