### ISSUE TITLE
JSON Schema: extensions/epub/properties.schema.json "spread" missing "portrait"?

### ISSUE THREAD

**Issue by danielweck** [readium/webpub-manifest#24]
https://github.com/readium/webpub-manifest/blob/917c83e798e3eda42b3e9d0dc92f0fef31b16211/schema/extensions/epub/properties.schema.json#L46-L55

https://github.com/readium/webpub-manifest/blob/917c83e798e3eda42b3e9d0dc92f0fef31b16211/schema/extensions/epub/metadata.schema.json#L37-L46

**Comment by danielweck** [comment]
Maps to EPUB `rendition:spread-portrait`

**Comment by HadrienGardeur** [comment]
From the EPUB spec:

> Reading Systems SHOULD treat the value “portrait” as a synonym of “both” and create spreads regardless of orientation.

We don't define portrait either in [the EPUB extension](https://readium.org/webpub-manifest/extensions/epub.html#properties).

**Comment by danielweck** [comment]
The fact that they are synonyms does not mean that we should remove one of them, right?

Plus, this is a breaking change:

TypeScript:

https://github.com/readium/r2-shared-js/blob/41eb2bf265d0145ef17a6affd159f2e79ea6d7ed/src/parser/epub.ts#L1390-L1393

```typescript
```

https://github.com/readium/r2-shared-js/blob/41eb2bf265d0145ef17a6affd159f2e79ea6d7ed/src/parser/epub.ts#L1277-L1280

```javascript
            case "rendition:spread-portrait": {
                propertiesStruct.Spread = "portrait";
                break;
}
```

Go:

https://github.com/readium/r2-streamer-go/blob/e4bf2ff6f829c2e6a87d62d83e4edf7bb876859c/parser/epub.go#L417-L418

```go
case "rendition:spread":
rendition.Spread = meta.Data
```

https://github.com/readium/r2-streamer-go/blob/e4bf2ff6f829c2e6a87d62d83e4edf7bb876859c/parser/epub.go#L374-L375

```go
case "rendition:spread-portrait":
propertiesStruct.Spread = "portrait"
```

Swift:

https://github.com/readium/r2-streamer-swift/blob/de36714b6137ff73c7f2b46700363771322fbfba/Sources/parser/OPFParser.swift#L318-L319

```swift
case "rendition:spread-portrait":
properties.spread = "portrait"
```

https://github.com/readium/r2-streamer-swift/blob/de36714b6137ff73c7f2b46700363771322fbfba/Sources/parser/MetadataParser.swift#L53-L57

```swift
        if let renditionSpread = metas.first(where: { $0.attributes["property"] == "rendition:spread" }) {
            let spread = renditionSpread.string

            metadata.rendition.spread = RenditionSpread(rawValue: spread)
}
```

Kotlin:

```kotlin

```

**Comment by HadrienGardeur** [comment]
`portrait` is deprecated, we usually don't include deprecated properties or metadata.

**Comment by HadrienGardeur** [comment]
I've looked at the commit history and even all the way back to our initial commit in early 2017, `portrait` wasn't included: https://github.com/readium/webpub-manifest/commit/4e8bb7c3c1ba87e2d3ae7b13d488545bfffdfb7d#diff-d2af120839dd0010c08c91e6da2eb346R17

**Comment by danielweck** [comment]
For tracking purposes:
http://www.idpf.org/epub/31/spec/epub-packages.html#fxl-property-spread-portrait

> Use of the portrait value with the rendition:spread property is deprecated. The rendition:spread-portrait spine override is similarly deprecated.

**Comment by danielweck** [comment]
Conclusion: the JSON Schema is correct, all the Readium2 implementations must be updated, right?

**Comment by danielweck** [comment]
EPUB 3.2 is more relevant than my above 3.1 link:
https://w3c.github.io/publ-epub-revision/epub32/spec/epub-packages.html#spread-values

> The use of spreads only in portrait orientation is deprecated. Authors are advised to use the value "both" instead, as spreads that are readable in portrait orientation are also readable in landscape. Reading Systems SHOULD treat the value "portrait" as a synonym of "both" and create spreads regardless of orientation.

**Comment by HadrienGardeur** [comment]
> Conclusion: the JSON Schema is correct, all the Readium2 implementations must be updated, right?

That would be my conclusion as well.

**Comment by danielweck** [comment]
I fixed the TypeScript implementation:
https://github.com/readium/r2-shared-js/commit/1cbe0a55a1e881352209842ef7c78484f8be3be1

I'll file issues for Kotlin Go and Swift.

**Comment by danielweck** [comment]
Done:
https://github.com/readium/r2-streamer-go/issues/43
https://github.com/readium/r2-streamer-swift/issues/80
https://github.com/readium/r2-streamer-kotlin/issues/58
