### ISSUE TITLE
JSON Schema: extensions/epub/properties.schema.json missing "page" and "orientation"?

### ISSUE THREAD

**Issue by danielweck** [readium/webpub-manifest#25]
https://github.com/readium/webpub-manifest/blob/917c83e798e3eda42b3e9d0dc92f0fef31b16211/schema/extensions/epub/properties.schema.json

`orientation`: `auto | landscape | portrait`
(maps to EPUB `rendition:orientation-auto`, `rendition:orientation-landscape`, `rendition:orientation-portrait`)

`page`: `left | right | center`
(maps to EPUB `page-spread-left`, `page-spread-right`, `page-spread-center`)

**Comment by HadrienGardeur** [comment]
They're both defined in the core document, at: https://github.com/readium/webpub-manifest/blob/master/schema/properties.schema.json

**Comment by danielweck** [comment]
Sorry!
