### ISSUE TITLE
Host JSON-LD context documents on readium.org

### ISSUE THREAD

**Issue by HadrienGardeur** [readium/webpub-manifest#3]
The Readium Web Publication Manifest is based on JSON-LD and has currently two different external documents both pointing to the readium.org website.
These URIs currently return a 404.

Could we add a few routes and static documents to readium.org?

cc @rkwright @whmccoy

**Comment by rkwright** [comment]
@HadrienGardeur Sure.  Let me know where would like them and I will take care of it.

**Comment by HadrienGardeur** [comment]
@rkwright could we host https://github.com/readium/webpub-manifest/blob/master/contexts/default/context.jsonld as http://readium.org/webpub/default.jsonld ?

**Comment by rkwright** [comment]
@HadrienGardeur That would be a new page, webpub, correct?  I'm trying to figure out where I would put that new page.  About and Participate don't seem quite right.  Creating a whole new submenu for one document seems like overkill.  Let me think a little more and we can discuss briefly at the meeting today.

**Comment by HadrienGardeur** [comment]
We don't really need this to show up at all while navigating on the readium.org website, we just need the ability to host this static file on our domain.

**Comment by HadrienGardeur** [comment]
The default context is currently available at http://readium.org/webpub-manifest/contexts/default/context.jsonld

This is not ideal, but I could reorganize the repo to have the default context document at http://readium.org/webpub-manifest/default.jsonld

**Comment by HadrienGardeur** [comment]
Any thoughts on this? cc @llemeurfr @rkwright

**Comment by llemeurfr** [comment]
Redirects on Github pages[ involves plug-ins](https://help.github.com/articles/redirects-on-github-pages/). 

IMO we'd better modify the location of the schema files and change their official URL, as @HadrienGardeur proposed in [his comment above](https://github.com/readium/webpub-manifest/issues/3#issuecomment-407121074). 
It also means that we'll have to change these URLs in every R2 streamer.

**Comment by danielweck** [comment]
Preferably secure https:// for readium.org
... but at this point in time there are problems with the domain registration, DNS redirect, etc., as documented here:
https://github.com/readium/readium-test-files/issues/8
(I made a couple of comments about Jekyll canonical URL as well, and using HTTP CORS)
I just wanted to bring this to your attention, before committing to the proposed URL change.
Right now I am not aware of implementations that need to fetch (HTTP request) the JSON-LD context from within the constrained security model of a webpage, but this may be useful in the near future ... so enabling secure HTTPS from the get-go would be wise.

**Comment by HadrienGardeur** [comment]
+1 for secure URLs. Any timeline on that?

I'll move the default context to a new location and start updating examples.

We also need to keep in mind that this is mostly a "nice to have" feature (I don't think any client is currently processing our manifest as JSON-LD).
