### ISSUE TITLE
Location of the @type property

### ISSUE THREAD

**Issue by llemeurfr** [readium/webpub-manifest#31]
The @type property is defined in the `metadata` structure[ in our spec](https://github.com/readium/webpub-manifest). It is a core JSON-LD property. 

[Reading the JSON-LD spec](https://w3c.github.io/json-ld-syntax/#specifying-the-type), it seems it should rather be defined at the root of the JSON-LD structure, as a sibling of `@id` and `@context`. 

Which one is right?

**Comment by HadrienGardeur** [comment]
We can do whatever we want (the RDF output is the same) and so far we've minimized the impact of JSON-LD in our core structure to strictly `@context`.

There is no valid reason to change this right now, `@type` should remain defined in `metadata`.
