### ISSUE TITLE
Divina compliance - "transitions"

### ISSUE THREAD

**Issue by chocolatkey** [readium/webpub-manifest#36]
In the divina extension document, under [level 1 compliance](https://github.com/readium/webpub-manifest/blob/master/extensions/divina.md#level-1), "Support for transitions" is a requirement.

What are "transitions"? It isn't hyperlinked, Ctrl + F lead to no results, and it is the only occurrence in the repository according to GitHub's search.

**Comment by llemeurfr** [comment]
Hi Henry, you're totally right, I have to add the whole section asap to the spec (it is currently in a working doc, but already implemented in the Android Divina module).

**Comment by HadrienGardeur** [comment]
Well... to be fair this part is still under discussions and I don't think it should be added as-is to the current draft.

I would rather remove mentions right now and re-introduce it in the future when it's fully baked.

**Comment by llemeurfr** [comment]
mmmh I disagree on this: now that it is implemented, let's expose it and enhance it if needed.

**Comment by HadrienGardeur** [comment]
It wasn't properly discussed IMO, doesn't matter if it's implemented or not, we need to be careful about what we add.

**Comment by chocolatkey** [comment]
I'll just ignore it for now then...

**Comment by chocolatkey** [comment]
@llemeurfr I was looking around the divina reader in the kotlin app, and was curious if the source of the pixijs-based reader is available somewhere?

**Comment by llemeurfr** [comment]
@chocolatkey, the code is open-source and available on the Readium Github as https://github.com/readium/divina-player-js.
