### ISSUE TITLE
Extracting EPUB encryption into a DRM extension

### ISSUE THREAD

**Issue by mickael-menu** [readium/webpub-manifest#42]
Currently, the encryption JSON schema [is part of the EPUB extension](https://readium.org/webpub-manifest/schema/extensions/epub/properties.schema.json).

Accordingly, the type [is named with the EPUB prefix](https://github.com/readium/r2-shared-swift/blob/cb2420f4dee0cc8cd55dce59329ab1f87cca01af/r2-shared-swift/Publication/Web%20Publication/Extensions/EPUB/EPUBEncryption.swift#L16) in the Swift project.

But now with LCPDF and soon audiobooks, this model is not limited to EPUB anymore, so I suggest extracting it to a new `DRM` extension.

**Comment by HadrienGardeur** [comment]
Now that we've divided extensions into modules and profiles, we could definitely move the `encrypted` property to its own module.

**Comment by llemeurfr** [comment]
I totally agree. I'll do it when I take a look at what Hadrien did last week.
