### ISSUE TITLE
Editing needed to clarify EPUB presentation+layout

### ISSUE THREAD

**Issue by jccr** [readium/webpub-manifest#56]
This looks incomplete:
https://readium.org/webpub-manifest/extensions/epub.html#layout

It's vaguely clear that its a new property for Link. It was not understood to me that it's also available for Metadata, without [looking at the schema](https://github.com/readium/webpub-manifest/blob/master/schema/extensions/epub/metadata.schema.json) first.

**Comment by HadrienGardeur** [comment]
This is covered in the following PR: #89
