### ISSUE TITLE
Improve JSON Schema

### ISSUE THREAD

**Issue by HadrienGardeur** [readium/webpub-manifest#8]
Our first draft for our JSON Schema is missing the following things:

- [x] Validate the presence of at least one `self` link
- [x] Validate that `templated` is set to `true` when a URI template is used in a link object
- [x] Validate the presence of type for `readingOrder` and `resources` items
- [x] Validation for languages (in language maps or in language)
- [x] Validate extensibility based on collection model
- [x] Validation for `properties`
- [x] Validation for `subject`

**Comment by HadrienGardeur** [comment]
For languages, I think that the best option is to validate against a regexp.

**Comment by HadrienGardeur** [comment]
It's also unclear to me if for the `self` link this would be better expressed using `dependencies`.

**Comment by danielweck** [comment]
Related issues:
https://github.com/readium/webpub-manifest/issues/13
https://github.com/readium/webpub-manifest/issues/14
https://github.com/readium/webpub-manifest/issues/15
https://github.com/readium/webpub-manifest/issues/16
